export type NodeType =
  | "territory"
  | "idea"
  | "question"
  | "person"
  | "venture"
  | "paper"
  | "experiment"
  | "technology"
  | "podcast-episode"
  | "prediction"
  | "essay"
  | "dataset"
  | "resource";

export type NodeRef = {
  type: NodeType;
  slug: string;
};

export type RelationType =
  | "researches"
  | "founded"
  | "supports"
  | "challenges"
  | "tests"
  | "applies"
  | "discusses"
  | "interviewed-in"
  | "related-to"
  | "generated-by"
  | "derived-from"
  | "emerges-from"
  | "belongs-to";

export type RelationRecord = {
  from: NodeRef;
  type: RelationType;
  to: NodeRef;
  note?: string;
};

export const relationTypeLabels: Record<RelationType, string> = {
  researches: "Researches",
  founded: "Founded",
  supports: "Supports",
  challenges: "Challenges",
  tests: "Tests",
  applies: "Applies",
  discusses: "Discusses",
  "interviewed-in": "Interviewed in",
  "related-to": "Related to",
  "generated-by": "Generated by",
  "derived-from": "Derived from",
  "emerges-from": "Emerges from",
  "belongs-to": "Part of"
};

export type EpistemicStatus = "fact" | "interpretation" | "hypothesis" | "prediction" | "speculation";

export const epistemicStatusLabels: Record<EpistemicStatus, string> = {
  fact: "Fact",
  interpretation: "Interpretation",
  hypothesis: "Hypothesis",
  prediction: "Prediction",
  speculation: "Speculation"
};

export function refEquals(a: NodeRef, b: NodeRef) {
  return a.type === b.type && a.slug === b.slug;
}

export function refKey(ref: NodeRef) {
  return `${ref.type}:${ref.slug}`;
}
