"use client";

import { useEffect, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { completeMission } from "@/app/admin/execution/actions";

type Row = Record<string, unknown>;
const inputClass = "mt-2 min-h-11 w-full rounded-md border border-line bg-graphite px-3 py-2 text-sm text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-signal";

export function ActiveMission({ mission }: { mission: Row }) {
  const router = useRouter(); const [pending, startTransition] = useTransition(); const [paused, setPaused] = useState(false); const [now, setNow] = useState(Date.now()); const [review, setReview] = useState(false); const [error, setError] = useState("");
  const startedAt = new Date(String(mission.started_at)).getTime();
  useEffect(() => { if (paused) return; const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, [paused]);
  const elapsed = Math.max(0, Math.floor((now - startedAt) / 1000)); const tasks = (mission.execution_mission_tasks as Row[] ?? []).sort((a, b) => Number(a.sort_order) - Number(b.sort_order)); const project = mission.execution_projects as { name?: string } | undefined;
  const submit = (formData: FormData) => startTransition(async () => { setError(""); const result = await completeMission({ missionId: String(mission.id), outcomeAchieved: formData.get("outcome") === "yes", actualMetric: String(formData.get("actualMetric") ?? ""), confidenceAfter: Number(formData.get("confidenceAfter")), learning: String(formData.get("learning") ?? ""), assumptionUpdate: String(formData.get("assumptionUpdate") ?? ""), nextMissionSuggestion: String(formData.get("nextMission") ?? ""), evidence: formData.get("evidenceTitle") ? [{ type: String(formData.get("evidenceType")), title: String(formData.get("evidenceTitle")), description: String(formData.get("evidenceDescription")), url: String(formData.get("evidenceUrl") ?? ""), metricName: String(formData.get("metricName") ?? ""), metricValue: String(formData.get("metricValue") ?? ""), visibility: String(formData.get("visibility")) }] : [] }); if (!result.ok) setError(result.error); else router.refresh(); });
  return <div className="grid gap-6"><section className="rounded-lg border border-signal/25 bg-signal/[0.045] p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="font-mono text-xs uppercase tracking-[0.22em] text-signal">{project?.name ?? "Project"} · {String(mission.mission_type)}</p><h2 className="mt-3 max-w-3xl text-3xl font-semibold text-white">{String(mission.title)}</h2><p className="mt-4 max-w-3xl leading-7 text-steel">{String(mission.desired_outcome)}</p></div><div className="text-right"><p className="font-mono text-3xl text-white">{String(Math.floor(elapsed / 3600)).padStart(2,"0")}:{String(Math.floor((elapsed % 3600) / 60)).padStart(2,"0")}:{String(elapsed % 60).padStart(2,"0")}</p><p className="mt-1 text-xs text-steel">{String(mission.estimated_minutes)} min planned · energy {String(mission.energy)}</p></div></div><div className="mt-6 flex flex-wrap gap-3"><span className="rounded-md border border-line px-3 py-2 text-xs text-steel">Risk: {String(mission.primary_risk)}</span><span className="rounded-md border border-line px-3 py-2 text-xs text-steel">Metric: {String(mission.success_metric_target)}</span></div></section>
    <section className="grid gap-3">{tasks.map((task, index) => <label key={String(task.id)} className="flex gap-4 rounded-lg border border-line bg-white/[0.035] p-5"><input type="checkbox" className="mt-1 size-5 accent-teal-300" /><span><span className="font-semibold text-white">{index + 1}. {String(task.title)}</span><span className="mt-1 block text-sm leading-6 text-steel">{String(task.description)} · {String(task.estimated_minutes)} min</span></span></label>)}</section>
    <section className="grid gap-4 rounded-lg border border-line p-5 md:grid-cols-2"><div><h3 className="text-sm font-semibold text-white">Expected evidence</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-steel">{(mission.expected_evidence as Array<{ description: string }> ?? []).map((item) => <li key={item.description}>{item.description}</li>)}</ul></div><div><h3 className="text-sm font-semibold text-white">Definition of done</h3><p className="mt-3 text-sm leading-6 text-steel">{String(mission.definition_of_done)}</p></div></section>
    <div className="flex gap-3"><button type="button" onClick={() => setPaused(!paused)} className="min-h-11 rounded-md border border-line px-5 text-sm text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-signal">{paused ? "Resume" : "Pause"}</button><button type="button" onClick={() => setReview(true)} className="min-h-11 rounded-md bg-signal px-5 text-sm font-semibold text-ink focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white">Complete mission</button></div>
    {review ? <form action={submit} className="rounded-lg border border-line bg-panel/80 p-6" aria-busy={pending}><h2 className="text-2xl font-semibold text-white">Completion review</h2><div className="mt-5 grid gap-5 md:grid-cols-2"><label className="text-sm text-steel">Was the outcome achieved?<select name="outcome" className={inputClass}><option value="yes">Yes</option><option value="no">No</option></select></label><label className="text-sm text-steel">Confidence after execution (1–10)<input name="confidenceAfter" type="text" inputMode="numeric" defaultValue="7" required className={inputClass} /></label></div><label className="mt-5 block text-sm text-steel">Actual metric achieved<input name="actualMetric" required className={inputClass} /></label><label className="mt-5 block text-sm text-steel">What was learned?<textarea name="learning" required rows={3} className={inputClass} /></label><label className="mt-5 block text-sm text-steel">What assumption changed?<textarea name="assumptionUpdate" required rows={3} className={inputClass} /></label><label className="mt-5 block text-sm text-steel">Next logical mission<textarea name="nextMission" rows={2} className={inputClass} /></label>
      <fieldset className="mt-6 rounded-md border border-line p-4"><legend className="px-2 text-sm font-semibold text-white">Evidence produced (optional)</legend><div className="grid gap-4 md:grid-cols-2"><label className="text-sm text-steel">Type<select name="evidenceType" className={inputClass}><option value="deployment">Deployment</option><option value="customer_feedback">Customer feedback</option><option value="revenue">Revenue</option><option value="usage">Usage</option><option value="research">Research</option><option value="content">Content</option><option value="benchmark">Benchmark</option><option value="other">Other</option></select></label><label className="text-sm text-steel">Visibility<select name="visibility" className={inputClass}><option value="private">Private</option><option value="portfolio">Portfolio</option><option value="public">Public</option></select></label><label className="text-sm text-steel">Title<input name="evidenceTitle" className={inputClass} /></label><label className="text-sm text-steel">URL<input name="evidenceUrl" type="url" inputMode="url" className={inputClass} /></label><label className="text-sm text-steel md:col-span-2">Description<textarea name="evidenceDescription" rows={2} className={inputClass} /></label><label className="text-sm text-steel">Metric name<input name="metricName" className={inputClass} /></label><label className="text-sm text-steel">Metric value<input name="metricValue" className={inputClass} /></label></div></fieldset>
      {error ? <p className="mt-4 text-sm text-red-200" role="alert">{error}</p> : null}<div className="mt-6 flex gap-3"><button disabled={pending} type="submit" className="min-h-11 rounded-md bg-signal px-5 text-sm font-semibold text-ink disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white">{pending ? "Completing…" : "Complete and store evidence"}</button><button type="button" onClick={() => setReview(false)} className="min-h-11 px-4 text-sm text-steel focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-signal">Cancel</button></div></form> : null}
  </div>;
}
