"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useRef, useState } from "react";
const commands = [{ label: "Generate today’s mission", href: "/admin/execution" }, { label: "Start current mission", href: "/admin/execution" }, { label: "Complete mission", href: "/admin/execution/today" }, { label: "Add evidence", href: "/admin/execution/today" }, { label: "Open project context", href: "/admin/execution/context" }, { label: "Review this week", href: "/admin/sales/review" }, { label: "Generate investor evidence summary", href: "/admin/sales/evidence" }];
export function ExecutionCommandPalette() {
  const pathname = usePathname(); const [open, setOpen] = useState(false); const trigger = useRef<HTMLButtonElement>(null);
  useEffect(() => { const key = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); setOpen((value) => !value); } if (event.key === "Escape") { setOpen(false); trigger.current?.focus(); } }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, []);
  if (!pathname.startsWith("/admin/execution")) return null;
  return <><button ref={trigger} type="button" onClick={() => setOpen(true)} className="fixed bottom-5 right-5 z-40 min-h-11 rounded-md border border-line bg-graphite px-4 text-xs text-steel shadow-lg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-signal" aria-label="Open execution command palette">⌘K · Commands</button>{open ? <div className="fixed inset-0 z-50 flex items-start justify-center bg-ink/80 px-4 pt-24 backdrop-blur-sm" role="dialog" aria-modal="true" aria-label="Execution commands" onMouseDown={(event) => { if (event.currentTarget === event.target) setOpen(false); }}><div className="w-full max-w-lg rounded-lg border border-line bg-panel p-3 shadow-xl"><div className="flex items-center justify-between px-3 py-2"><h2 className="font-semibold text-white">Execution commands</h2><button type="button" onClick={() => setOpen(false)} className="min-h-10 px-3 text-sm text-steel focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-signal">Close</button></div><nav className="mt-2 grid gap-1">{commands.map((command) => <Link key={command.label} href={command.href} onClick={() => setOpen(false)} className="flex min-h-11 items-center rounded-md px-3 text-sm text-steel hover:bg-white/5 hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-signal">{command.label}</Link>)}</nav></div></div> : null}</>;
}
