"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { generateMission, persistMission } from "@/app/admin/execution/actions";
import type { GeneratedMission, ProjectContext } from "@/lib/execution-types";

const inputClass = "mt-2 min-h-11 w-full rounded-md border border-line bg-graphite px-3 py-2 text-sm text-white placeholder:text-steel/60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-signal";
const stages = ["Reviewing project context", "Identifying highest-risk assumption", "Designing evidence-producing mission", "Checking scope against available time"];
const adjustments = ["simplify the mission", "make the mission more commercial", "make the mission more technical", "make the mission more customer-focused", "reduce scope", "fit mission into less time"];

export function MissionGenerator({ projects }: { projects: ProjectContext[] }) {
  const router = useRouter(); const [pending, startTransition] = useTransition();
  const [input, setInput] = useState({ projectId: projects[0]?.id ?? "", availableTimeMinutes: 120, energy: "3" as const, currentPriority: "", currentBottleneck: "", notes: "" });
  const [mission, setMission] = useState<GeneratedMission | null>(null); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const run = (options?: { adjustment?: string; field?: keyof GeneratedMission }) => startTransition(async () => { setError(""); setMessage(""); const result = await generateMission(input, { ...options, currentMission: mission ?? undefined }); if (!result.ok) setError(result.error); else setMission(result.data.mission); });
  const save = (status: "draft" | "active") => { if (!mission) return; startTransition(async () => { setError(""); const result = await persistMission({ projectId: input.projectId, energy: input.energy, mission, status }); if (!result.ok) setError(result.error); else if (status === "active") router.push("/admin/execution/today"); else setMessage("Draft saved."); }); };
  const update = <K extends keyof GeneratedMission>(key: K, value: GeneratedMission[K]) => setMission((current) => current ? { ...current, [key]: value } : current);
  const field = (label: string, key: keyof GeneratedMission, value: string) => <section className="rounded-lg border border-line bg-white/[0.035] p-5"><div className="flex items-center justify-between gap-3"><label htmlFor={`mission-${key}`} className="text-sm font-semibold text-white">{label}</label><button type="button" onClick={() => run({ field: key })} disabled={pending} className="min-h-10 rounded-md px-3 text-xs text-signal hover:bg-white/5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-signal">Regenerate</button></div><textarea id={`mission-${key}`} value={value} onChange={(event) => update(key, event.target.value as never)} rows={3} className={inputClass} /></section>;

  return <div className="grid gap-8">
    <form onSubmit={(event) => { event.preventDefault(); run(); }} className="rounded-lg border border-line bg-panel/75 p-5 sm:p-7" aria-busy={pending}>
      <h2 className="text-xl font-semibold text-white">Mission inputs</h2><p className="mt-2 text-sm text-steel">Project, available time, and energy are the only required inputs.</p>
      <div className="mt-6 grid gap-5 md:grid-cols-3"><label className="text-sm text-steel">Project *<select required value={input.projectId} onChange={(e) => setInput({ ...input, projectId: e.target.value })} className={inputClass}>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label className="text-sm text-steel">Available time *<select value={input.availableTimeMinutes} onChange={(e) => setInput({ ...input, availableTimeMinutes: Number(e.target.value) })} className={inputClass}>{[30,45,60,90,120,180,240,360,480].map((minutes) => <option key={minutes} value={minutes}>{minutes < 60 ? `${minutes} min` : `${minutes / 60} hr`}</option>)}</select></label><label className="text-sm text-steel">Energy *<select value={input.energy} onChange={(e) => setInput({ ...input, energy: e.target.value as typeof input.energy })} className={inputClass}><option value="1">1 · Depleted</option><option value="2">2 · Low</option><option value="3">3 · Steady</option><option value="4">4 · Strong</option><option value="5">5 · Peak</option></select></label></div>
      <div className="mt-5 grid gap-5 md:grid-cols-2"><label className="text-sm text-steel">Current priority (optional)<textarea value={input.currentPriority} onChange={(e) => setInput({ ...input, currentPriority: e.target.value })} rows={2} className={inputClass} /></label><label className="text-sm text-steel">Current bottleneck (optional)<textarea value={input.currentBottleneck} onChange={(e) => setInput({ ...input, currentBottleneck: e.target.value })} rows={2} className={inputClass} /></label></div><label className="mt-5 block text-sm text-steel">Relevant notes (optional)<textarea value={input.notes} onChange={(e) => setInput({ ...input, notes: e.target.value })} rows={3} className={inputClass} /></label>
      <button type="submit" disabled={pending || !input.projectId} className="mt-6 min-h-11 rounded-md bg-signal px-5 py-2.5 text-sm font-semibold text-ink transition-colors hover:bg-volt disabled:cursor-not-allowed disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white">{pending ? "Generating mission…" : "Generate today’s mission"}</button>
      {pending ? <div className="mt-5 grid gap-2 sm:grid-cols-2" role="status">{stages.map((stage) => <div key={stage} className="animate-pulse rounded-md border border-line px-3 py-2 text-xs text-steel">{stage}</div>)}</div> : null}
      {error ? <div className="mt-5 rounded-md border border-red-400/30 bg-red-400/10 p-4 text-sm text-red-100" role="alert"><p>{error}</p><button type="button" onClick={() => run()} className="mt-2 min-h-10 text-signal underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-signal">Retry</button></div> : null}{message ? <p className="mt-4 text-sm text-signal" role="status">{message}</p> : null}
    </form>
    {!mission && !pending ? <div className="rounded-lg border border-dashed border-line p-8 text-center"><h2 className="text-lg font-semibold text-white">No proposal yet</h2><p className="mt-2 text-sm text-steel">Generate a mission to review, edit, and start it.</p></div> : null}
    {mission ? <div className="grid gap-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-mono text-xs uppercase tracking-[0.24em] text-signal">AI proposal</p><h2 className="mt-2 text-2xl font-semibold text-white">Review every field before starting.</h2></div><div className="flex flex-wrap gap-2">{adjustments.map((item) => <button key={item} type="button" disabled={pending} onClick={() => run({ adjustment: item })} className="min-h-10 rounded-md border border-line px-3 py-2 text-xs text-steel hover:border-signal/40 hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-signal">{item}</button>)}</div></div>
      {field("Mission", "missionTitle", mission.missionTitle)}{field("Strategic reason", "whyItMatters", mission.whyItMatters)}
      <div className="grid gap-5 md:grid-cols-2"><section className="rounded-lg border border-line bg-white/[0.035] p-5"><label htmlFor="mission-type" className="text-sm font-semibold text-white">Mission type</label><input id="mission-type" readOnly value={mission.missionType} className={inputClass} /></section><section className="rounded-lg border border-line bg-white/[0.035] p-5"><label htmlFor="primary-risk" className="text-sm font-semibold text-white">Risk reduced</label><input id="primary-risk" readOnly value={mission.primaryRisk} className={inputClass} /></section></div>
      {field("Assumption tested", "assumptionBeingTested", mission.assumptionBeingTested)}{field("Desired outcome", "desiredOutcome", mission.desiredOutcome)}{field("Definition of done", "definitionOfDone", mission.definitionOfDone)}
      <section className="rounded-lg border border-line bg-white/[0.035] p-5"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold text-white">Three tasks</h3><button type="button" onClick={() => run({ field: "tasks" })} className="min-h-10 px-3 text-xs text-signal focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-signal">Regenerate</button></div><div className="mt-3 grid gap-3">{mission.tasks.map((task, index) => <div key={index} className="grid gap-2 rounded-md border border-line p-4"><input aria-label={`Task ${index + 1} title`} value={task.title} onChange={(e) => update("tasks", mission.tasks.map((item, i) => i === index ? { ...item, title: e.target.value } : item))} className={inputClass} /><textarea aria-label={`Task ${index + 1} description`} value={task.description} onChange={(e) => update("tasks", mission.tasks.map((item, i) => i === index ? { ...item, description: e.target.value } : item))} className={inputClass} /><label className="text-xs text-steel">Minutes<input type="text" inputMode="numeric" value={task.estimatedMinutes} onChange={(e) => update("tasks", mission.tasks.map((item, i) => i === index ? { ...item, estimatedMinutes: Number(e.target.value) || 0 } : item))} className={`${inputClass} max-w-28`} /></label></div>)}</div></section>
      <section className="rounded-lg border border-line bg-white/[0.035] p-5"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold text-white">Expected evidence</h3><button type="button" onClick={() => run({ field: "expectedEvidence" })} className="min-h-10 px-3 text-xs text-signal focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-signal">Regenerate</button></div>{mission.expectedEvidence.map((evidence, index) => <div key={index} className="mt-3 flex gap-3"><span className="pt-3 font-mono text-[11px] uppercase text-signal">{evidence.type.replace("_", " ")}</span><input aria-label={`Evidence ${index + 1}`} value={evidence.description} onChange={(e) => update("expectedEvidence", mission.expectedEvidence.map((item, i) => i === index ? { ...item, description: e.target.value } : item))} className={inputClass} /></div>)}</section>
      <div className="grid gap-5 md:grid-cols-2"><section className="rounded-lg border border-line bg-white/[0.035] p-5"><h3 className="text-sm font-semibold text-white">Success metric</h3><input aria-label="Success metric name" value={mission.successMetric.name} onChange={(e) => update("successMetric", { ...mission.successMetric, name: e.target.value })} className={inputClass} /><input aria-label="Success metric target" value={mission.successMetric.target} onChange={(e) => update("successMetric", { ...mission.successMetric, target: e.target.value })} className={inputClass} /></section><section className="rounded-lg border border-line bg-white/[0.035] p-5"><h3 className="text-sm font-semibold text-white">Time and confidence</h3><p className="mt-3 text-sm text-steel">{mission.recommendedTimeMinutes} minutes · confidence {mission.confidenceBefore}/10</p></section></div>
      {field("Public-build angle", "publicBuildAngle", mission.publicBuildAngle)}<section className="rounded-lg border border-line bg-white/[0.035] p-5"><h3 className="text-sm font-semibold text-white">Do not work on</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-sm text-steel">{mission.doNotWorkOn.map((item) => <li key={item}>{item}</li>)}</ul></section><p className="rounded-md border border-signal/20 bg-signal/5 p-4 text-sm leading-6 text-steel">{mission.reasoningSummary}</p>
      <div className="sticky bottom-4 flex flex-wrap gap-3 rounded-lg border border-line bg-graphite/95 p-4 shadow-lg backdrop-blur"><button type="button" disabled={pending} onClick={() => save("active")} className="min-h-11 rounded-md bg-signal px-5 text-sm font-semibold text-ink focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white">Start mission</button><button type="button" disabled={pending} onClick={() => save("draft")} className="min-h-11 rounded-md border border-line px-5 text-sm text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-signal">Save as draft</button><button type="button" disabled={pending} onClick={() => run()} className="min-h-11 rounded-md px-4 text-sm text-signal focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-signal">Regenerate all</button><button type="button" onClick={() => setMission(null)} className="min-h-11 rounded-md px-4 text-sm text-steel focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-signal">Cancel</button></div>
    </div> : null}
  </div>;
}
