"use client";
import { useState, useTransition } from "react";
import { updateProjectContext } from "@/app/admin/execution/actions";
import type { ProjectContext } from "@/lib/execution-types";
const inputClass = "mt-2 min-h-11 w-full rounded-md border border-line bg-graphite px-3 py-2 text-sm text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-signal";
const lines = (value: string) => value.split("\n").map((item) => item.trim()).filter(Boolean);
export function ProjectContextEditor({ projects }: { projects: ProjectContext[] }) {
  const [selected, setSelected] = useState(projects[0]); const [pending, startTransition] = useTransition(); const [status, setStatus] = useState("");
  if (!selected) return <p className="text-steel">No projects are available.</p>;
  const set = (key: keyof ProjectContext, value: unknown) => setSelected({ ...selected, [key]: value });
  const save = () => startTransition(async () => { const result = await updateProjectContext(selected); setStatus(result.ok ? "Project context saved." : result.error); });
  return <div className="grid gap-6"><label className="max-w-sm text-sm text-steel">Project<select value={selected.id} onChange={(e) => setSelected(projects.find((item) => item.id === e.target.value) ?? selected)} className={inputClass}>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><form onSubmit={(e) => { e.preventDefault(); save(); }} className="grid gap-5 rounded-lg border border-line bg-panel/70 p-6"><div className="grid gap-5 md:grid-cols-2"><label className="text-sm text-steel">Stage<input value={selected.stage} onChange={(e) => set("stage", e.target.value)} className={inputClass} /></label><label className="text-sm text-steel">Description<textarea value={selected.description} onChange={(e) => set("description", e.target.value)} rows={2} className={inputClass} /></label></div>{([['Target customer','targetCustomer'],['Customer problem','customerProblem'],['Value proposition','valueProposition'],['Current priority','currentPriority'],['Current bottleneck','currentBottleneck'],['Relevant notes','contextNotes']] as const).map(([label,key]) => <label key={key} className="text-sm text-steel">{label}<textarea value={selected[key]} onChange={(e) => set(key, e.target.value)} rows={3} className={inputClass} /></label>)}<div className="grid gap-5 md:grid-cols-2">{([['Current metrics','currentMetrics'],['Current risks','currentRisks'],['Active milestones','activeMilestones'],['Open assumptions','openAssumptions'],['Product URLs','productUrls'],['Repository URLs','repositoryUrls']] as const).map(([label,key]) => <label key={key} className="text-sm text-steel">{label} <span className="text-xs">(one per line)</span><textarea value={selected[key].join("\n")} onChange={(e) => set(key, lines(e.target.value))} rows={4} className={inputClass} /></label>)}</div><div><button type="submit" disabled={pending} className="min-h-11 rounded-md bg-signal px-5 text-sm font-semibold text-ink disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white">{pending ? "Saving…" : "Save project context"}</button>{status ? <p className="mt-3 text-sm text-signal" role="status">{status}</p> : null}</div></form></div>;
}
