import Link from "next/link";
import { relatedRefs } from "@/lib/graph/registry";
import { resolveNode } from "@/lib/graph/resolve";
import type { NodeRef } from "@/lib/graph/types";

const relationLabels: Record<string, string> = {
  researches: "Researches",
  founded: "Founded",
  supports: "Supports",
  challenges: "Challenges",
  tests: "Tests",
  applies: "Applies",
  discusses: "Discusses",
  "interviewed-in": "Interviewed in",
  "related-to": "Related to",
  "generated-by": "Generated by",
  "derived-from": "Derived from",
  "emerges-from": "Emerges from",
  "belongs-to": "Part of"
};

export function RelatedNodes({ nodeRef, heading = "Connected nodes" }: { nodeRef: NodeRef; heading?: string }) {
  const related = relatedRefs(nodeRef)
    .map((item) => ({ ...item, resolved: resolveNode(item.ref) }))
    .filter((item) => item.resolved !== undefined);

  if (related.length === 0) {
    return null;
  }

  return (
    <div>
      <p className="font-mono text-xs uppercase tracking-[0.28em] text-signal">{heading}</p>
      <div className="mt-6 grid gap-3 sm:grid-cols-2">
        {related.map((item) => (
          <Link
            key={`${item.direction}-${item.relationType}-${item.resolved!.href}`}
            href={item.resolved!.href}
            className="block rounded-lg border border-line bg-white/[0.035] p-5 transition hover:border-signal/35 active:border-signal/50"
          >
            <p className="font-mono text-[11px] uppercase tracking-[0.18em] text-steel">
              {relationLabels[item.relationType] ?? item.relationType}
            </p>
            <h3 className="mt-2 text-base font-semibold text-white">{item.resolved!.title}</h3>
            <p className="mt-2 text-sm leading-6 text-steel">{item.resolved!.summary}</p>
          </Link>
        ))}
      </div>
    </div>
  );
}
